name: TryHackMe Update Badge

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'   # executa diariamente (UTC)

permissions:
  contents: write

jobs:
  tryhackme-badge-update:
    name: Update TryHackMe badge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure assets folder exists
        run: mkdir -p ./assets

      - name: Install Puppeteer and Chrome
        run: |
          npm install puppeteer@24.26.0
          npx puppeteer browsers install chrome
        env:
          PUPPETEER_CACHE_DIR: /home/runner/.cache/puppeteer

      - name: Configure Chrome path
        run: |
          echo "export CHROME_PATH=$(find /home/runner/.cache/puppeteer -name chrome -type f | head -n 1)" >> $GITHUB_ENV
          echo "Chrome path set to: $CHROME_PATH"

      - name: Run TryHackMe badge workflow
        uses: p4p1/tryhackme-badge-workflow@main
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ env.CHROME_PATH }}
        with:
          username: "hypes999"
          user_public_id: "3586204"
          image_path: "./assets/thm_propic.png"
          use_static_image: "false"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
