name: TryHackMe Update Badge

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'   # diária (UTC)

permissions:
  contents: write

jobs:
  tryhackme-badge-update:
    name: Update TryHackMe badge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure assets folder exists
        run: mkdir -p ./assets

      - name: Install Chrome for Puppeteer
        run: npx puppeteer browsers install chrome

      - name: Run TryHackMe badge workflow
        uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "hypes999"
          user_public_id: "3586204"     # <<-- substitui pelo teu ID público TryHackMe (número)
          image_path: "./assets/thm_propic.png"
          use_static_image: "false"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
